# 计算机模拟第一周作业

## 题目描述

假设：
$$X_i = (AX_{i-1}) \ mod \ M, \qquad i \geq 1$$
$$Y_j = (BY_{j-1}) \ mod \ M, \qquad j \geq 1$$
其中 $AB \ mod \ M = 1$，并且 $X_0,Y_0 \leq M - 1$。

证明：用 B 做参数产生的随机序列和用 A 做参数产生的随机序列一样，只是次序相反（倒序）。

## 证明
欲证明题目中的结论，只需证明：对任意 $i, j \in Z_+$，若 $X_i = Y_{j+1}$，则：
$$X_{i+1} = Y_j$$

由于:
$$X_{i+1} = (AX_i) \ mod \ M$$
$$Y_{j+1} = (BY_j) \ mod \ M$$
利用 $AB \ mod \ M = 1$，可得：
$$AY_{j+1} \ mod \ M = A(BY_j) \ mod \ M = Y_j \ mod \ Y = Y_j$$
最后一个等号的成立是由于 $Y_j \leq M - 1$。
因此，$Y_j = AX_i \ mod \ M = X_{i+1}$，结论成立。

根据对称性，对任意 $i, j \in Z_+$，若 $X_{i+1} = Y_j$，则：
$$X_i = Y_{j+1}$$
题目中结论得证。

## 验证

以下是乘同余随机数生成器的实现

In [10]:
import numpy as np

# 乘同余随机数生成器
def rand_mul_mod(X0, A, M, N):
    X = np.zeros(N)
    X[0] = X0
    for i in range(1, N):
        X[i] = (A * X[i - 1]) % M
    return X

### M 为质数

选取 $M = 31, \ A = 4, \ B = 8$ 来验证。

In [22]:
# 生成 X
X = rand_mul_mod(1, 5, 29, 15)
X

array([ 1.,  5., 25.,  9., 16., 22., 23., 28., 24.,  4., 20., 13.,  7.,
        6.,  1.])

In [30]:
# 生成 Y
Y = rand_mul_mod(1, 6, 29, 15)
Y

array([ 1.,  6.,  7., 13., 20.,  4., 24., 28., 23., 22., 16.,  9., 25.,
        5.,  1.])

In [31]:
# 验证顺序相反
X == Y[::-1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

### M不为质数

选取 $M = 10, \ A = 3, \ B = 7$ 来验证：

In [35]:
# 生成 U
U = rand_mul_mod(2, 3, 10, 10)
U

array([2., 6., 8., 4., 2., 6., 8., 4., 2., 6.])

In [36]:
# 生成 V
V = rand_mul_mod(6, 7, 10, 10)
V

array([6., 2., 4., 8., 6., 2., 4., 8., 6., 2.])

In [37]:
# 验证顺序相反
U == V[::-1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])